### ISSUE TITLE
All accepted blocks should be rootblocks

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/iota-core#616] opened 2023-12-07 14:13 UTC
Make `optsRootBlocksEvictionDelay` a protocol parameter: The value needs to be sufficiently large - MaxCommittableAge comes to mind but maybe more?

**Comment by jonastheis** [comment] 2023-12-08 10:19
The main issue we're having is imo that root blocks are not (entirely) objective. The issue is twofold: 
1. Currently we only mark a block as root block if it is accepted and is referenced by an accepted block in a future slot. Technically, according to this definition a block can always become a root block from any point in the future. The problem here is that it now depends on eviction and when slots become evicted before that is not possible anymore (which is subjective, nodes evict at different times). 
2. The second is as you state `optsRootBlocksEvictionDelay`, which should indeed be a protocol parameter or implicitly part of the protocol rules.

## Status quo
<img width="1154" alt="image" src="https://github.com/iotaledger/iota-core/assets/4181434/206cf8a3-a54c-41ba-847a-020174716f39">

red blocks: root blocks according to the current definition
green block: not clear what happens with this block and its parent. especially problematic when another node wants to warp sync and thus doesn't see the green block's parent as a root block.


## Suggested solution
Instead of having subjective root blocks, I'd suggest making all accepted/committed blocks of a slot become root blocks. But only for blocks up to `slot + maxCommittableAge`. This rule is objective, simple and it is always clear which blocks can be referenced from a future block. 

<img width="1263" alt="image" src="https://github.com/iotaledger/iota-core/assets/4181434/fcd06295-42f0-4a83-a9d0-a7b203eda5d5">


An exception to this rule is when the chain halts and is revived: here the commitment the `block A` points to is empty. So the parent of `block A` should be any block within the **last non-empty slot** before the empty commitment of `block A`.

<img width="1000" alt="image" src="https://github.com/iotaledger/iota-core/assets/4181434/a7533517-a057-4122-a153-1de7b1b64792">


## Conclusion
From PoV of blocks this would mean: the oldest parent you can select is in `slot - maxCommittableAge` if the commitment that the block commits to is non-empty. If the commitment is empty (reviving the chain) then the parents need to be out of the last non-empty slot in the chain. All of these should be objective.

This change should actually simplify the entire `engine/eviction` package. 
Another note is the snapshot: We probably need to export all blockIDs (+ commitmendIDs?) starting from `slot - maxCommittableAge`.

**Comment by karimodm** [comment] 2023-12-11 10:27
The proposed approach to fix this is:

- All accepted blocks should be considered potential rootblocks.
- Remove eviction state
  - We track last evicted slot and last non-empty slot directly in the engine / protocol
  - Rootblocks will be loaded directly from storage:
    - If the block's slot is non-empty then we search in the `[ slot - maxCommittableAge, slot ]` blocks' buckets.
    - Otherwise we look _only_ in the `last non empty slot` bucket.

**Closed as completed** 2023-12-12 15:54 UTC
