### ISSUE TITLE
Mana overflow while running the docker network

### ISSUE THREAD

**Issue by daria305** [iotaledger/iota-core#411] opened 2023-10-09 08:17 UTC
This error popped up while running the docker network while implementing and testing account creation on `feat/account-tooling` branch

docker-network-peer_master2-1  | 2023-10-08T14:14:27Z   ERROR   Protocol        app/component.go:115    Error in Protocol: integer under- or overflow: 13835058055282886524 + 4611686018427387903: overflow when adding stored, potential and decayed BIC for account 0x375358f92cc94750669598b0aaa55a6ff73310b90710e1fad524c0f911be0fea: failed to retrieve mana on account 0x375358f92cc94750669598b0aaa55a6ff73310b90710e1fad524c0f911be0fea for slot 3: metrics: engine (c760b43f)

**Comment by piotrm50** [comment] 2023-10-13 12:28
Duplicate of #415

**Closed by piotrm50** 2023-10-13 12:28 UTC
