### ISSUE TITLE
Check for Expiration Feature correct?

### ISSUE THREAD

**Issue by muXxer** [iotaledger/iota-core#413] opened 2023-10-09 09:01 UTC
There should never be a possibility to unlock outputs with Expiration Unlock Condition by two different parties at the same time.
I'm not sure if the current "pastBoundSlot" and "futureBoundSlot" prevents that in every case.

Can we have a short discussion about that?

**Comment by PhilippGackstatter** [comment] 2023-10-23 07:55
This is explained with an example in [TIP-38](https://github.com/iotaledger/tips-draft/blob/tip38/tips/TIP-0038/tip-0038.md#expiration-unlock-condition-index-bounds) and as explained in there, there is no overlapping period of time where both can unlock.

**Comment by cyberphysic4l** [comment] 2023-10-25 08:11
@muXxer if you are satisfied we can close this issue.

**Comment by muXxer** [comment] 2023-11-01 16:16
After a call with @cyberphysic4l , we agreed that there is the theoretical possibility that someone can backdate Blocks.
This should also be taken into account in the "deadzone" calculation.

Maybe the `pastBoundedSlotIndex` is `commitmentInput.Slot + 2*protocolParameters.MaxCommittableAge()`

PS: Can we add the diagram to the TIP for better explanation? Maybe also add the possible "backdate" range for Blocks in the diagram itself?

**Comment by cyberphysic4l** [comment] 2023-11-07 09:58
"Backdating" blocks a singificant amount is only possible when we have liveness. The most that someone can backdate a block is to `ATT-LivenessThresholdUpperBound`, so if we have liveness (`ATT ~= WallClockTime`), then the most someone could backdate their block is by `LivenessThresholdUpperBound`. 

Additionaly, the only time that backdating has any consequence is if we have liveness. Assume some application (for example, a layer 2 chain) relies on an expired output being consumed. The application should only consider the expired output as consumed and act on that if the output is at least accepted, but ideally until is committed, confirmed or finalized. The higher the level of finality the application waits for, the more difficult it is for the receiver address owner to backdate a block and revert the consumption of the expired output. For example, if the application waits for commitment of the expired output being consumed, then it is impossible for the receiver address to subsequently consume that unless it forces a chain switch, because the receiver address can only consume the output in an earlier slot than the return address can consume it, and all such earlier slots are already committed. If the application only waits for acceptance of the expired output consumption, a malicious owner of the receiver address could technically issue a backdated block shortly after `ATT-LivenessThresholdUpperBound`, but this block would be less likely to be selected as a tip, and because the majority of online validators already accepted the expired output consumption, they should not accept the backdated receiver consumption becuase it is a conflict. The only way the receiver address could revert the other conflict is by having support of a majority of other validators to revert it. In conclusion, it is very difficult to backdate even with just acceptance, and becomes more difficult if you wait for higher levels of finality. This attack relates to the fundamental fact that the best we can do at approximating time is the block timestamp, it is meant to be very difficult to falsify that. 

**Note**: ISC is not susceptible to such a backdating attack anyway because they are the receiver Address of the expiration locked outputs they deal with, they are not waiting for it to expire so they can consume it.

**Comment by PhilippGackstatter** [comment] 2023-11-07 14:32
Here is an illustration of a block backdated by one slot, where both `Address` and `Return Address` could unlock an output with an Expiration Unlock Condition.
![Accounts-Backdating Blocks drawio](https://github.com/iotaledger/iota-core/assets/18741416/91081ac6-3d96-44db-92e8-177d2ebb6d8e)

Howevever, as @cyberphysic4l mentioned, as long as the `Return Address` owner does what is recommended and waits for some level of finality, then the higher the level of finality the less likely it is to result in a double spend.

**Closed by PhilippGackstatter** 2023-11-07 14:32 UTC
